/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;


import Desenho.DesenhoFita;
import Desenho.VisualizacaoPassoTuring;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Vinicius
 */
public class PassoPassoTuringMulti extends javax.swing.JFrame {

    /**
     * Creates new form PassoPasso
     */
    private ArrayList<Estado> estados;    
    private int passo = 2;
    private Estado atual, inicial;
    private String[][] fita, aux; 
    private int posicao[];
    private int nFitas;
    private JPanel[] painelFitas;
    DesenhoFita f;
    
    public PassoPassoTuringMulti(ArrayList<Estado> estados, String[][] fita, Estado atual, int nFitas) {
        this.estados = estados;       
        this.fita = fita;  
        this.atual = atual;
        this.nFitas = nFitas;
        inicial = atual;
        
        posicao = new int[nFitas];
        for(int i = 0; i < nFitas; i++)
           posicao[i] = 4999;
        
        aux = new String[nFitas][];        
        
        copiaFita();
        initComponents();
        
        JPanel a;
        int y = 0;
        painelFitas = new JPanel[nFitas];
        
        for(int i = 0; i < nFitas; i++){
            a = new DesenhoFita(aux[i], posicao[i]-4);
            painelFitas[i] = a;
            a.setSize(new java.awt.Dimension(156, 26));          
            a.setLocation(10, y+10);          
            jPanel3.add(a);
            y += 33;
        }
        
        ((VisualizacaoPassoTuring)jPanel1).setEstados(estados, atual);
        jPanel1.repaint();
        for(int i = 0; i < nFitas; i++)
            painelFitas[i].repaint();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new VisualizacaoPassoTuring(estados, atual);
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Simulação passo a passo");
        setPreferredSize(new java.awt.Dimension(800, 710));
        setSize(new java.awt.Dimension(800, 900));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 350));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Próximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(51,153,255));
        jButton1.setEnabled(true);
        ((VisualizacaoPassoTuring)jPanel1).setEstados(estados, inicial);
        jPanel1.repaint();
        copiaFita();
        atual = inicial;
        jButton1.setEnabled(true);
        for(int i = 0; i < nFitas; i++){
              ((DesenhoFita)painelFitas[i]).setFita(aux[i], 4995);           
               painelFitas[i].repaint(); 
        }
        for(int i = 0; i < nFitas; i++)
            posicao[i] = 4999;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String transicao = "";
        int verifica = 0, aux2=0, aux3=0;

        for(Transicao t : atual.getTransicoes())
          for(String s : t.getSimbolo()){
             for(int j = 0; j < nFitas; j++){  
                if(aux[j][posicao[j]].equals(s.substring(aux2, aux2+1)))
                    aux3 += 1;
                 aux2 += 12; 
                }
                if(aux3 == nFitas){
                    atual = t.getEstadoDestino();
                    transicao = s;
                    verifica++;
                    aux2 = aux3 = 0;
                    break;
                 }             
             aux2 = aux3 = 0;
          }
        
        
        //movimenta a fita
        if(verifica != 0){

            verifica = 0;

            aux2 = aux3 = 0;            
             
            
            for(int k = 0; k < nFitas; k++){
                
                switch(transicao.substring(aux2+8, aux2+9)){
                        case "R":   aux[k][posicao[k]] = transicao.substring(aux2+4, aux2+5);
                                    posicao[k]++;                                 
                                    break;

                        case "S":   aux[k][posicao[k]] = transicao.substring(aux2+4, aux2+5);                                   
                                    break;

                        case "L":   aux[k][posicao[k]] = transicao.substring(aux2+4, aux2+5);
                                    posicao[k]--;                                
                                    break;
                }
                aux2 += 12;
            }
                
            ((VisualizacaoPassoTuring)jPanel1).setEstados(estados, atual);
            jPanel1.repaint();
           
            for(int i = 0; i < nFitas; i++){
               ((DesenhoFita)painelFitas[i]).setFita(aux[i], posicao[i]-4);           
                painelFitas[i].repaint(); 
            }

        }

        else{
            jPanel3.setBackground(new Color (255,0,0));
            jButton1.setEnabled(false);
            return;
        }

        if(atual.isFinal()){
            jPanel3.setBackground(new Color (0,204,0));
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void copiaFita(){        
        
        for(int i = 0; i < nFitas; i++)
           aux[i] = new String[10000];
        
        for(int j = 0; j < nFitas; j++)
           for(int i = 0; i < fita[j].length; i++)
                aux[j][i] = fita[j][i];    
    }
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
