/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JCheckBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Vinicius
 */
public class DetectarBordaTela extends javax.swing.JPanel {

    /**
     * Creates new form ProcessamentoCanal
     */
    public DetectarBordaTela() {
        initComponents();
    }  

    public JCheckBox getcB1() {
        return cB1;
    }

    public JCheckBox getcC1() {
        return cC1;
    } 

    public JCheckBox getcG1() {
        return cG1;
    }

    public JCheckBox getcH1() {
        return cH1;
    }

    public JCheckBox getcI1() {
        return cI1;
    }

    public JCheckBox getcM1() {
        return cM1;
    }  
   

    public JCheckBox getcQ1() {
        return cQ1;
    } 

    public JCheckBox getcR1() {
        return cR1;
    }

    public JCheckBox getcS1() {
        return cS1;
    }

    public JCheckBox getcV1() {
        return cV1;
    }   

    public JCheckBox getcY1() {
        return cY1;
    } 

    public JCheckBox getcYY1() {
        return cYY1;
    } 

    public JCheckBox getcCb() {
        return cCb;
    }

    public JCheckBox getcCr() {
        return cCr;
    }

    public JCheckBox getcYYY1() {
        return cYYY1;
    }  

    public JRadioButton getrAnd() {
        return rAnd;
    }

    public JRadioButton getrColorido() {
        return rColorido;
    }

    public JRadioButton getrMagnitude() {
        return rMagnitude;
    }

    public JRadioButton getrMaximo() {
        return rMaximo;
    }

    public JRadioButton getrMedia() {
        return rMedia;
    }

    public JRadioButton getrMinimo() {
        return rMinimo;
    }

    public JRadioButton getrOr() {
        return rOr;
    }

    public JRadioButton getrXor() {
        return rXor;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sCanais1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cR1 = new javax.swing.JCheckBox();
        cG1 = new javax.swing.JCheckBox();
        cB1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        cY1 = new javax.swing.JCheckBox();
        cI1 = new javax.swing.JCheckBox();
        cQ1 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        cH1 = new javax.swing.JCheckBox();
        cS1 = new javax.swing.JCheckBox();
        cV1 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        cC1 = new javax.swing.JCheckBox();
        cM1 = new javax.swing.JCheckBox();
        cYY1 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        cYYY1 = new javax.swing.JCheckBox();
        cCb = new javax.swing.JCheckBox();
        cCr = new javax.swing.JCheckBox();
        jPanel16 = new javax.swing.JPanel();
        rColorido = new javax.swing.JRadioButton();
        rMagnitude = new javax.swing.JRadioButton();
        rMaximo = new javax.swing.JRadioButton();
        rMinimo = new javax.swing.JRadioButton();
        rMedia = new javax.swing.JRadioButton();
        rOr = new javax.swing.JRadioButton();
        rAnd = new javax.swing.JRadioButton();
        rXor = new javax.swing.JRadioButton();

        buttonGroup1.add(rColorido);
        buttonGroup1.add(rMagnitude);
        buttonGroup1.add(rMaximo);
        buttonGroup1.add(rMinimo);
        buttonGroup1.add(rMedia);
        buttonGroup1.add(rOr);
        buttonGroup1.add(rAnd);
        buttonGroup1.add(rXor);
        buttonGroup1.setSelected(rColorido.getModel(), true);

        sCanais1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Canais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "RGB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cR1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cR1.setText("R ");

        cG1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cG1.setText("G ");

        cB1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cB1.setText("B ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cG1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cB1)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cG1)
                    .addComponent(cR1)
                    .addComponent(cB1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "YIQ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cY1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cY1.setText("Y");

        cI1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cI1.setText("I");

        cQ1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cQ1.setText("Q");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cY1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cI1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cQ1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cI1)
                    .addComponent(cY1)
                    .addComponent(cQ1))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "HSV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cH1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cH1.setText("H");

        cS1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cS1.setText("S");

        cV1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cV1.setText("V");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cS1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cV1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cS1)
                    .addComponent(cH1)
                    .addComponent(cV1))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CMY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cC1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cC1.setText("C");

        cM1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cM1.setText("M");

        cYY1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYY1.setText("Y");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cYY1)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cM1)
                    .addComponent(cC1)
                    .addComponent(cYY1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "YCbCr", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cYYY1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYYY1.setText("Y");

        cCb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cCb.setText("Cb");

        cCr.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cCr.setText("Cr");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cYYY1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cCr)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCb)
                    .addComponent(cYYY1)
                    .addComponent(cCr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sCanais1Layout = new javax.swing.GroupLayout(sCanais1);
        sCanais1.setLayout(sCanais1Layout);
        sCanais1Layout.setHorizontalGroup(
            sCanais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sCanais1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sCanais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sCanais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(sCanais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sCanais1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sCanais1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sCanais1Layout.setVerticalGroup(
            sCanais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sCanais1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sCanais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(sCanais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Técnica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        rColorido.setText("Colorido");

        rMagnitude.setText("Magnitude");

        rMaximo.setText("Máximo");

        rMinimo.setText("Mínimo");

        rMedia.setText("Média");

        rOr.setText("Or");

        rAnd.setText("And");

        rXor.setText("Xor");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rMaximo)
                    .addComponent(rMinimo)
                    .addComponent(rMedia)
                    .addComponent(rOr)
                    .addComponent(rColorido)
                    .addComponent(rMagnitude))
                .addGap(88, 88, 88))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rAnd)
                    .addComponent(rXor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(rColorido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rMagnitude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rMaximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rMinimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rMedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rOr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rAnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rXor)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sCanais1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sCanais1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cB1;
    private javax.swing.JCheckBox cC1;
    private javax.swing.JCheckBox cCb;
    private javax.swing.JCheckBox cCr;
    private javax.swing.JCheckBox cG1;
    private javax.swing.JCheckBox cH1;
    private javax.swing.JCheckBox cI1;
    private javax.swing.JCheckBox cM1;
    private javax.swing.JCheckBox cQ1;
    private javax.swing.JCheckBox cR1;
    private javax.swing.JCheckBox cS1;
    private javax.swing.JCheckBox cV1;
    private javax.swing.JCheckBox cY1;
    private javax.swing.JCheckBox cYY1;
    private javax.swing.JCheckBox cYYY1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton rAnd;
    private javax.swing.JRadioButton rColorido;
    private javax.swing.JRadioButton rMagnitude;
    private javax.swing.JRadioButton rMaximo;
    private javax.swing.JRadioButton rMedia;
    private javax.swing.JRadioButton rMinimo;
    private javax.swing.JRadioButton rOr;
    private javax.swing.JRadioButton rXor;
    private javax.swing.JPanel sCanais1;
    // End of variables declaration//GEN-END:variables
}
