/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JCheckBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Vinicius
 */
public class EqualizacaoTela extends javax.swing.JPanel {

    /**
     * Creates new form ProcessamentoCanal
     */
    public EqualizacaoTela() {
        initComponents();
    }  

    public JCheckBox getcB1() {
        return cB1;
    }

    public JCheckBox getcC1() {
        return cC1;
    } 

    public JCheckBox getcG1() {
        return cG1;
    }

    public JCheckBox getcH1() {
        return cH1;
    }

    public JCheckBox getcI1() {
        return cI1;
    }

    public JCheckBox getcM1() {
        return cM1;
    }  
   

    public JCheckBox getcQ1() {
        return cQ1;
    } 

    public JCheckBox getcR1() {
        return cR1;
    }

    public JCheckBox getcS1() {
        return cS1;
    }

    public JCheckBox getcV1() {
        return cV1;
    }   

    public JCheckBox getcY1() {
        return cY1;
    } 

    public JCheckBox getcYY1() {
        return cYY1;
    }

    public JCheckBox getcB2() {
        return cB2;
    }

    public JCheckBox getcB3() {
        return cB3;
    }

    public JCheckBox getcC2() {
        return cC2;
    }

    public JCheckBox getcC3() {
        return cC3;
    }

    public JCheckBox getcG2() {
        return cG2;
    }

    public JCheckBox getcG3() {
        return cG3;
    }

    public JCheckBox getcH2() {
        return cH2;
    }

    public JCheckBox getcH3() {
        return cH3;
    }

    public JCheckBox getcI2() {
        return cI2;
    }

    public JCheckBox getcI3() {
        return cI3;
    }

    public JCheckBox getcM2() {
        return cM2;
    }

    public JCheckBox getcM3() {
        return cM3;
    }

    public JCheckBox getcQ2() {
        return cQ2;
    }

    public JCheckBox getcQ3() {
        return cQ3;
    }

    public JCheckBox getcR2() {
        return cR2;
    }

    public JCheckBox getcR3() {
        return cR3;
    }

    public JCheckBox getcS2() {
        return cS2;
    }

    public JCheckBox getcS3() {
        return cS3;
    }

    public JCheckBox getcV2() {
        return cV2;
    }

    public JCheckBox getcV3() {
        return cV3;
    }

    public JCheckBox getcY2() {
        return cY2;
    }

    public JCheckBox getcY3() {
        return cY3;
    }

    public JCheckBox getcYY2() {
        return cYY2;
    }

    public JCheckBox getcYY3() {
        return cYY3;
    }

    public JCheckBox getcCb_2() {
        return cCb_2;
    }

    public JCheckBox getcCb_3() {
        return cCb_3;
    }

    public JCheckBox getcCr_2() {
        return cCr_2;
    }

    public JCheckBox getcCr_3() {
        return cCr_3;
    }

    public JCheckBox getcYYY1() {
        return cYYY1;
    }

    public JCheckBox getcYYY_2() {
        return cYYY_2;
    }

    public JCheckBox getcYYY_3() {
        return cYYY_3;
    }

    public JCheckBox getcCb1() {
        return cCb1;
    }

    public JCheckBox getcCr1() {
        return cCr1;
    }   

    public JRadioButton getrAnd() {
        return rAnd;
    }

    public JRadioButton getrColorido() {
        return rColorido;
    }

    public JRadioButton getrMagnitude() {
        return rMagnitude;
    }

    public JRadioButton getrMaximo() {
        return rMaximo;
    }

    public JRadioButton getrMedia() {
        return rMedia;
    }

    public JRadioButton getrMinimo() {
        return rMinimo;
    }

    public JRadioButton getrOr() {
        return rOr;
    }

    public JRadioButton getrXor() {
        return rXor;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sCanais = new javax.swing.JPanel();
        canal1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cR1 = new javax.swing.JCheckBox();
        cG1 = new javax.swing.JCheckBox();
        cB1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        cY1 = new javax.swing.JCheckBox();
        cI1 = new javax.swing.JCheckBox();
        cQ1 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        cH1 = new javax.swing.JCheckBox();
        cS1 = new javax.swing.JCheckBox();
        cV1 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        cC1 = new javax.swing.JCheckBox();
        cM1 = new javax.swing.JCheckBox();
        cYY1 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        cYYY1 = new javax.swing.JCheckBox();
        cCb1 = new javax.swing.JCheckBox();
        cCr1 = new javax.swing.JCheckBox();
        canal2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cR2 = new javax.swing.JCheckBox();
        cG2 = new javax.swing.JCheckBox();
        cB2 = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        cY2 = new javax.swing.JCheckBox();
        cI2 = new javax.swing.JCheckBox();
        cQ2 = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        cH2 = new javax.swing.JCheckBox();
        cS2 = new javax.swing.JCheckBox();
        cV2 = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        cC2 = new javax.swing.JCheckBox();
        cM2 = new javax.swing.JCheckBox();
        cYY2 = new javax.swing.JCheckBox();
        jPanel24 = new javax.swing.JPanel();
        cYYY_2 = new javax.swing.JCheckBox();
        cCb_2 = new javax.swing.JCheckBox();
        cCr_2 = new javax.swing.JCheckBox();
        canal3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cR3 = new javax.swing.JCheckBox();
        cG3 = new javax.swing.JCheckBox();
        cB3 = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        cY3 = new javax.swing.JCheckBox();
        cI3 = new javax.swing.JCheckBox();
        cQ3 = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        cH3 = new javax.swing.JCheckBox();
        cS3 = new javax.swing.JCheckBox();
        cV3 = new javax.swing.JCheckBox();
        jPanel17 = new javax.swing.JPanel();
        cC3 = new javax.swing.JCheckBox();
        cM3 = new javax.swing.JCheckBox();
        cYY3 = new javax.swing.JCheckBox();
        jPanel25 = new javax.swing.JPanel();
        cYYY_3 = new javax.swing.JCheckBox();
        cCb_3 = new javax.swing.JCheckBox();
        cCr_3 = new javax.swing.JCheckBox();
        jPanel16 = new javax.swing.JPanel();
        rColorido = new javax.swing.JRadioButton();
        rMagnitude = new javax.swing.JRadioButton();
        rMaximo = new javax.swing.JRadioButton();
        rMinimo = new javax.swing.JRadioButton();
        rMedia = new javax.swing.JRadioButton();
        rOr = new javax.swing.JRadioButton();
        rAnd = new javax.swing.JRadioButton();
        rXor = new javax.swing.JRadioButton();

        buttonGroup1.add(rColorido);
        buttonGroup1.add(rMagnitude);
        buttonGroup1.add(rMaximo);
        buttonGroup1.add(rMinimo);
        buttonGroup1.add(rMedia);
        buttonGroup1.add(rOr);
        buttonGroup1.add(rAnd);
        buttonGroup1.add(rXor);
        buttonGroup1.setSelected(rColorido.getModel(), true);

        sCanais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Canais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        canal1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Canal 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "RGB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cR1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cR1.setText("R ");

        cG1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cG1.setText("G ");

        cB1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cB1.setText("B ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cG1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cB1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cG1)
                    .addComponent(cR1)
                    .addComponent(cB1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "YIQ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cY1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cY1.setText("Y");

        cI1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cI1.setText("I");

        cQ1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cQ1.setText("Q");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cY1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cI1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cQ1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cI1)
                    .addComponent(cY1)
                    .addComponent(cQ1))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "HSV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cH1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cH1.setText("H");

        cS1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cS1.setText("S");

        cV1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cV1.setText("V");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cS1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cV1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cS1)
                    .addComponent(cH1)
                    .addComponent(cV1))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CMY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cC1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cC1.setText("C");

        cM1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cM1.setText("M");

        cYY1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYY1.setText("Y");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cYY1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cM1)
                    .addComponent(cC1)
                    .addComponent(cYY1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "YCbCr", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cYYY1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYYY1.setText("Y");

        cCb1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cCb1.setText("Cb");

        cCr1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cCr1.setText("Cr");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cYYY1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cCr1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCb1)
                    .addComponent(cYYY1)
                    .addComponent(cCr1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout canal1Layout = new javax.swing.GroupLayout(canal1);
        canal1.setLayout(canal1Layout);
        canal1Layout.setHorizontalGroup(
            canal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(canal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        canal1Layout.setVerticalGroup(
            canal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        canal2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Canal 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "RGB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cR2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cR2.setText("R ");

        cG2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cG2.setText("G ");

        cB2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cB2.setText("B ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cR2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cG2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cB2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cG2)
                    .addComponent(cR2)
                    .addComponent(cB2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "YIQ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cY2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cY2.setText("Y");

        cI2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cI2.setText("I");

        cQ2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cQ2.setText("Q");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cY2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cI2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cQ2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cI2)
                    .addComponent(cY2)
                    .addComponent(cQ2))
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "HSV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cH2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cH2.setText("H");

        cS2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cS2.setText("S");

        cV2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cV2.setText("V");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cH2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cS2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cV2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cS2)
                    .addComponent(cH2)
                    .addComponent(cV2))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CMY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cC2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cC2.setText("C");

        cM2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cM2.setText("M");

        cYY2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYY2.setText("Y");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cC2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cM2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cYY2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cM2)
                    .addComponent(cC2)
                    .addComponent(cYY2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "YCbCr", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cYYY_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYYY_2.setText("Y");

        cCb_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cCb_2.setText("Cb");

        cCr_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cCr_2.setText("Cr");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cYYY_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCb_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cCr_2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCb_2)
                    .addComponent(cYYY_2)
                    .addComponent(cCr_2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout canal2Layout = new javax.swing.GroupLayout(canal2);
        canal2.setLayout(canal2Layout);
        canal2Layout.setHorizontalGroup(
            canal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canal2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(canal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        canal2Layout.setVerticalGroup(
            canal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canal2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        canal3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Canal 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "RGB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cR3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cR3.setText("R ");

        cG3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cG3.setText("G ");

        cB3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cB3.setText("B ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cR3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cG3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cB3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cG3)
                    .addComponent(cR3)
                    .addComponent(cB3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "YIQ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cY3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cY3.setText("Y");

        cI3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cI3.setText("I");

        cQ3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cQ3.setText("Q");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cY3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cI3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cQ3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cI3)
                    .addComponent(cY3)
                    .addComponent(cQ3))
                .addContainerGap())
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "HSV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cH3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cH3.setText("H");

        cS3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cS3.setText("S");

        cV3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cV3.setText("V");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cH3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cS3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cV3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cS3)
                    .addComponent(cH3)
                    .addComponent(cV3))
                .addContainerGap())
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CMY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cC3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cC3.setText("C");

        cM3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cM3.setText("M");

        cYY3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYY3.setText("Y");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cC3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cM3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cYY3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cM3)
                    .addComponent(cC3)
                    .addComponent(cYY3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "YCbCr", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        cYYY_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYYY_3.setText("Y");

        cCb_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cCb_3.setText("Cb");

        cCr_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cCr_3.setText("Cr");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(cYYY_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCb_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cCr_3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCb_3)
                    .addComponent(cYYY_3)
                    .addComponent(cCr_3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout canal3Layout = new javax.swing.GroupLayout(canal3);
        canal3.setLayout(canal3Layout);
        canal3Layout.setHorizontalGroup(
            canal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canal3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(canal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        canal3Layout.setVerticalGroup(
            canal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canal3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sCanaisLayout = new javax.swing.GroupLayout(sCanais);
        sCanais.setLayout(sCanaisLayout);
        sCanaisLayout.setHorizontalGroup(
            sCanaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sCanaisLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(canal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(canal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(canal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        sCanaisLayout.setVerticalGroup(
            sCanaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sCanaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sCanaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sCanaisLayout.createSequentialGroup()
                        .addGroup(sCanaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(canal2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(canal1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Técnica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        rColorido.setText("Colorido");

        rMagnitude.setText("Magnitude");

        rMaximo.setText("Máximo");

        rMinimo.setText("Mínimo");

        rMedia.setText("Média");

        rOr.setText("Or");

        rAnd.setText("And");

        rXor.setText("Xor");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rXor)
                    .addComponent(rAnd)
                    .addComponent(rOr)
                    .addComponent(rMedia)
                    .addComponent(rMaximo)
                    .addComponent(rMinimo)
                    .addComponent(rMagnitude)
                    .addComponent(rColorido))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rColorido)
                .addGap(18, 18, 18)
                .addComponent(rMagnitude)
                .addGap(18, 18, 18)
                .addComponent(rMaximo)
                .addGap(18, 18, 18)
                .addComponent(rMinimo)
                .addGap(18, 18, 18)
                .addComponent(rMedia)
                .addGap(18, 18, 18)
                .addComponent(rOr)
                .addGap(18, 18, 18)
                .addComponent(rAnd)
                .addGap(18, 18, 18)
                .addComponent(rXor)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sCanais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sCanais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cB1;
    private javax.swing.JCheckBox cB2;
    private javax.swing.JCheckBox cB3;
    private javax.swing.JCheckBox cC1;
    private javax.swing.JCheckBox cC2;
    private javax.swing.JCheckBox cC3;
    private javax.swing.JCheckBox cCb1;
    private javax.swing.JCheckBox cCb2;
    private javax.swing.JCheckBox cCb3;
    private javax.swing.JCheckBox cCb4;
    private javax.swing.JCheckBox cCb5;
    private javax.swing.JCheckBox cCb6;
    private javax.swing.JCheckBox cCb7;
    private javax.swing.JCheckBox cCb8;
    private javax.swing.JCheckBox cCb9;
    private javax.swing.JCheckBox cCb_2;
    private javax.swing.JCheckBox cCb_3;
    private javax.swing.JCheckBox cCr1;
    private javax.swing.JCheckBox cCr2;
    private javax.swing.JCheckBox cCr3;
    private javax.swing.JCheckBox cCr4;
    private javax.swing.JCheckBox cCr5;
    private javax.swing.JCheckBox cCr6;
    private javax.swing.JCheckBox cCr7;
    private javax.swing.JCheckBox cCr8;
    private javax.swing.JCheckBox cCr9;
    private javax.swing.JCheckBox cCr_2;
    private javax.swing.JCheckBox cCr_3;
    private javax.swing.JCheckBox cG1;
    private javax.swing.JCheckBox cG2;
    private javax.swing.JCheckBox cG3;
    private javax.swing.JCheckBox cH1;
    private javax.swing.JCheckBox cH2;
    private javax.swing.JCheckBox cH3;
    private javax.swing.JCheckBox cI1;
    private javax.swing.JCheckBox cI2;
    private javax.swing.JCheckBox cI3;
    private javax.swing.JCheckBox cM1;
    private javax.swing.JCheckBox cM2;
    private javax.swing.JCheckBox cM3;
    private javax.swing.JCheckBox cQ1;
    private javax.swing.JCheckBox cQ2;
    private javax.swing.JCheckBox cQ3;
    private javax.swing.JCheckBox cR1;
    private javax.swing.JCheckBox cR2;
    private javax.swing.JCheckBox cR3;
    private javax.swing.JCheckBox cS1;
    private javax.swing.JCheckBox cS2;
    private javax.swing.JCheckBox cS3;
    private javax.swing.JCheckBox cV1;
    private javax.swing.JCheckBox cV2;
    private javax.swing.JCheckBox cV3;
    private javax.swing.JCheckBox cY1;
    private javax.swing.JCheckBox cY2;
    private javax.swing.JCheckBox cY3;
    private javax.swing.JCheckBox cYY1;
    private javax.swing.JCheckBox cYY2;
    private javax.swing.JCheckBox cYY3;
    private javax.swing.JCheckBox cYYY1;
    private javax.swing.JCheckBox cYYY2;
    private javax.swing.JCheckBox cYYY3;
    private javax.swing.JCheckBox cYYY4;
    private javax.swing.JCheckBox cYYY5;
    private javax.swing.JCheckBox cYYY6;
    private javax.swing.JCheckBox cYYY7;
    private javax.swing.JCheckBox cYYY8;
    private javax.swing.JCheckBox cYYY9;
    private javax.swing.JCheckBox cYYY_2;
    private javax.swing.JCheckBox cYYY_3;
    private javax.swing.JPanel canal1;
    private javax.swing.JPanel canal2;
    private javax.swing.JPanel canal3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton rAnd;
    private javax.swing.JRadioButton rColorido;
    private javax.swing.JRadioButton rMagnitude;
    private javax.swing.JRadioButton rMaximo;
    private javax.swing.JRadioButton rMedia;
    private javax.swing.JRadioButton rMinimo;
    private javax.swing.JRadioButton rOr;
    private javax.swing.JRadioButton rXor;
    private javax.swing.JPanel sCanais;
    // End of variables declaration//GEN-END:variables
}
