/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Vinicius
 */
public class ImagemOriginal extends javax.swing.JFrame {
    
    private BufferedImage originalImage;   
    
    class Imagem extends JPanel {

	private Image img;

	public Imagem(Image img) {
		this.img = img;
		Dimension dim = new Dimension(img.getWidth(null)+17,
                                    img.getHeight(null)+40);		
		
		setSize(dim);
		
	}

	@Override
	protected void paintComponent(Graphics g) {
		super.paintComponent(g);
		g.drawImage(img, 0, 0, null);
	}
    }
    
    public ImagemOriginal(File arquivo) throws IOException {
        initComponents();
        originalImage = ImageIO.read(arquivo);           
    }
    
    public ImagemOriginal(Quadro quadro) throws IOException {
        initComponents();
        originalImage = quadro.getImagem();
        setTitle(quadro.getNome());        
    }

    public BufferedImage getOriginalImage() {
        return originalImage;
    }

    public void setOriginalImage(BufferedImage originalImage) {
        this.originalImage = originalImage;
    }   
    
    public void colocaImagem(){   
        Imagem i = new Imagem(originalImage); 
        add(i);
        setSize(i.getWidth(), i.getHeight());
        setLocationRelativeTo(null);
        setVisible(true); 
        this.setResizable(false);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imagem Original");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
