/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JLabel;

/**
 *
 * @author Vinicius
 */
public class LimiarTela extends javax.swing.JPanel {

    /**
     * Creates new form Threshold
     */
    private float lowT, highT, lOtsu;
    
    public LimiarTela(float lOtsu) {
        this.lOtsu = lOtsu;        
        initComponents();
        jSlider1.setValue(10);
        lOV.setText(Float.toString(lOtsu));       
        lIV.setText(Float.toString(lOtsu-10));
        lSV.setText(Float.toString(lOtsu+10));
    }

    public JLabel getlIV() {
        return lIV;
    }

    public JLabel getlSV() {
        return lSV;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        lI = new javax.swing.JLabel();
        lS = new javax.swing.JLabel();
        lSV = new javax.swing.JLabel();
        lIV = new javax.swing.JLabel();
        lOV = new javax.swing.JLabel();
        lO = new javax.swing.JLabel();

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setMajorTickSpacing(25);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        lI.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lI.setText("Limiar Inferior:");

        lS.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lS.setText("Limiar Superior:");

        lSV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lIV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lOV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lO.setText("Limiar encontrada em Otsu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lIV, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lSV, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lOV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lO)
                    .addComponent(lOV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lSV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lI)
                        .addComponent(lS))
                    .addComponent(lIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        lowT = -jSlider1.getValue();
        
        if(lOtsu+lowT < 0)
            lowT = 0;
        else
            lowT = lOtsu-jSlider1.getValue();
        
        highT = jSlider1.getValue();
        lIV.setText(Float.toString(lowT));
        lSV.setText(Float.toString(lOtsu+highT));
    }//GEN-LAST:event_jSlider1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lI;
    private javax.swing.JLabel lIV;
    private javax.swing.JLabel lO;
    private javax.swing.JLabel lOV;
    private javax.swing.JLabel lS;
    private javax.swing.JLabel lSV;
    // End of variables declaration//GEN-END:variables
}
