/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tela.java
 *
 * Created on 28/10/2013, 16:08:16
 */
package convexhull;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.util.ArrayList;

/**
 *
 * @author Danilo Medeiros Eler
 */
public class Tela extends javax.swing.JFrame {
    private ArrayList<Ponto> pontos = null;
    private int numPontos = 25;
    /** Creates new form Tela */
    public Tela() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        executar_Button = new javax.swing.JButton();
        convexHull_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto e Análise de Algoritmos - Prof. Danilo Medeiros Eler - Convex Hull - Divide and Conquer");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        executar_Button.setText("Gerar Pontos");
        executar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executar_ButtonActionPerformed(evt);
            }
        });

        convexHull_Button.setText("Convex Hull");
        convexHull_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convexHull_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(executar_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(convexHull_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executar_Button)
                    .addComponent(convexHull_Button))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executar_ButtonActionPerformed
        // TODO add your handling code here:
        pontos = new ArrayList<Ponto>();
        for (int i = 0; i < numPontos; i++) {                                               ///inverte o zero para o canto inferior esquerdo
            Ponto p = new Ponto((int) (20 + Math.random() * (jPanel1.getWidth()-70)), (int) (jPanel1.getHeight() - (20 + Math.random() * (jPanel1.getHeight()-70))));
            pontos.add(p);
        }
        //pontos colineares
       // pontos.add(new Ponto(jPanel1.getHeight()-50,50));
       // pontos.add(new Ponto(jPanel1.getHeight()-70,250));
       // pontos.add(new Ponto(jPanel1.getHeight()-150,150));
       // pontos.add(new Ponto(jPanel1.getHeight()-200,200));
       // pontos.add(new Ponto(jPanel1.getHeight()-250,250));

        BufferedImage imageBuffer = new BufferedImage(jPanel1.getWidth(), jPanel1.getHeight(), BufferedImage.TYPE_INT_RGB);

        Graphics2D g2Buffer = imageBuffer.createGraphics();
        g2Buffer.setColor(Color.WHITE);
        g2Buffer.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        g2Buffer.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        for (Ponto p:pontos){
            p.draw(imageBuffer);
        }
        g2Buffer.dispose();

        jPanel1.getGraphics().drawImage(imageBuffer, 0, 0, null);
    }//GEN-LAST:event_executar_ButtonActionPerformed

    private void convexHull_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convexHull_ButtonActionPerformed
        // TODO add your handling code here:
        ConvexHull cH = new ConvexHull(pontos);
        cH.execute();
        Poligono convexHull = cH.getConvexHullPoints();
        Graphics2D g2 = (Graphics2D) jPanel1.getGraphics();
        No aux = convexHull.ini;
        for (int i=0;i<convexHull.size;i++){
            Ponto p1 = aux.getP();
            Ponto p2 = aux.prox.getP();// convexHull.get(i+1);
            g2.drawLine(p1.getX(), p1.getY(), p2.getX(), p2.getY());
            aux = aux.prox;
        }
    }//GEN-LAST:event_convexHull_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convexHull_Button;
    private javax.swing.JButton executar_Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
